PR to merge Feature into development
UmairAhmad125/the-restaurant-page pull request #1
Opened 2021-01-25 14:08 UTC by UmairAhmad125

In this project, I created a minimalist restaurant page that contains.
- A landing page that welcomes users.
- A menu page that displays the menu.
- A contact us page that contains a simple contact form.

2021-01-25 17:35 UTC, bertil291utn requested changes
# **Status:** Changes requested 🟠 
<p align="center"> <img src="https://i.cubeupload.com/4HbSFK.jpg" alt="image" width="60" /> <br><strong>Not yet</strong> </p>

# Hey guys, you've been doing a great job, and also I hope you enjoyed coding.

### Your work is amazing.

However, in order to accomplish the actual page, you required to do these changes, listed below:
### General requirements
- Next projects, please don't; forget to add a commit message after a function or something relatable that you could mention in the commit message because it's not good practice to commit at the end of the project. Also when you have recurrent commit you could use a wide range to use git tool (rebase, merge, rollback some error)
- [ ] Add acknowledge section (if you have something ), giving credits to the inspirations page, or where you get information to build this project
- [ ] "Built with" section. Add links to each technology. Because when someone arrives at the README file it'd be great to know where to find this technology. Example![image](https://user-images.githubusercontent.com/24902525/105737460-f97a1400-5f03-11eb-974a-9cc89facb751.png)
* [ ] Necessary run common commands like `build`, `development` should be in `package.json` inside \`scripts'. Here is a basic example ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/restaurant_page/scripts_requirement.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59622983/))
```json
"scripts": {
    "dev": "webpack --mode development",
    "build": "webpack --mode production",
    "start": "webpack-dev-server --mode development --open"
  },
```
- [ ] It appends HTML elements to the `<div>` with `id=content` when the page is loaded (Use `document.createElement` and `document.appendChild` ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/restaurant_page/append_requirement.png) from [Odin](https://www.theodinproject.com/courses/javascript/lessons/restaurant-page))
  - Add an `index.html` file then use as root pointer to start all page, follow this [example](https://github.com/bertil291utn/restaurant-page) 


### OPTIONAL
- It'd be great to don't have the home link section in the navbar element, because when you land for the first time to the page you have already the home, and to return to the home page just clicking on the logo 
- Add the logo in the navbar section as a link to redirect to the index page 
- It'd be great to have on the home section an introduction. This page's great in that it should go to your portfolio, and to do that we need to add great information to display this page 
- Same for other pages add real information and actual images 
- Give a style to the form on the 'contact us' section 
- Use `export default <your object/function>` for all modules export,  because it's more readable 

### Summary
- Add more information, and real images and also update styling in the contact form element, because this project could be on your portfolio 
- Use ES6 syntax for import
- Add `index.html` to start as root file. Remember to add webpack configuration, pointing to the new index.html file, following the example 
- Add scripts to start and build its project
-  Don't forget to work with inline comments below this comment box.

***

Guys work on the requested changes above and request another review.
Good luck. 

> “Never stop, never conform until what is good becomes even better, and what’s better becomes excellent.”

2021-01-25 17:35 UTC, bertil291utn commented on src/js/navbar.js
> +export { navbar as default };
### Inline comments
- Remove inline comments, it's not good practice to leave code

2021-01-25 17:35 UTC, bertil291utn commented on src/js/index.js
> +
### Use ES6 syntax
- [ ] Use import for CSS files and remember to have a configuration for CSS files loader in webpack file

2021-01-26 08:29 UTC, mikenath223 requested changes
### Hello Team 👋

**Good work so far here. You did quite well here fixing most issues raised in the previous review.** 👍

However, let's make a few more fixes and we are good to go.

- Please refer to comments on the code.

### **STATUS: CHANGES REQUESTED** 👷‍♂️

Kindly fix these issues and request another review👍
Feel free to contact me on slack(michgolden) if you need further clarification.

**HAPPY CODING 🎉💻🎉**

**Michgolden Ukeje (CR)**

2021-01-26 08:30 UTC, mikenath223 commented on package.json
> +        "start": "webpack-dev-server --mode development --open"
- [ ] If the webpack dev server option is being used please include the `webpack-dev-server` package in the project.

2021-01-26 08:31 UTC, mikenath223 commented on src/css/style.css
> +  max-height: 300px !important;
- [ ] Kindly avoid using the !important rule in css as it doesn't meet the best practices requirements. Please remove it.

2021-01-26 08:31 UTC, mikenath223 commented on src/js/contact.js
> +  h1.appendChild(h1Text);
- [ ] Please change this function to es6 arrow function syntax.

2021-01-26 08:32 UTC, mikenath223 commented on src/js/menu.js
> +    const foodContainer = document.createElement('div');
- [ ] Also kindly change this function to es6 arrow function syntax too.

2021-01-26 08:32 UTC, mikenath223 commented on src/js/navbar.js
> +  const tabsCont = document.createElement('div');
- [ ] Also change this function to es6 arrow function syntax too.

2021-01-26 08:33 UTC, mikenath223 commented on src/js/page-load.js
> +  h1.appendChild(h1Text);
- [ ] Also change this function to es6 arrow function syntax.

2021-01-26 10:32 UTC, whiz25 approved these changes
## Approved :white_check_mark:
Good job guys. You changed all functions in the src folder to ES6 arrow functions as requested. Your codebase now looks clean and modern.
Please merge and proceed to the next milestone.


### Martin Afani

2021-01-27 06:59 UTC, merged